version: "4"

services:
  nats-server:
    image: nats:latest

  client-gateway:
    image: europe-southwest1-docker.pkg.dev/microservicios-dev-434019/img-registro-ms/client-gateway
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    image: europe-southwest1-docker.pkg.dev/microservicios-dev-434019/img-registro-ms/auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    image: europe-southwest1-docker.pkg.dev/microservicios-dev-434019/img-registro-ms/products-ms
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  payments-ms:
    image: europe-southwest1-docker.pkg.dev/microservicios-dev-434019/img-registro-ms/payments-ms
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${PAYMENTS_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_STRIPE_ENDPOINT_SECRET}

  orders-ms:
    image: europe-southwest1-docker.pkg.dev/microservicios-dev-434019/img-registro-ms/orders-ms
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}
